name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          submodules: true
      - uses: actions/setup-ruby@v1.1.1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update bundler
        run: gem install bundler -v 2.1.4
      - name: Install dependencies
        run: bundle install
      - name: Build and run tests
        run: bundle exec rake
      - name: Run rubocop
        run: bundle exec rubocop --fail-level=W
